# Backend service
[services.backend]
path = "backend"
start = "node server.js"

# Frontend service (if it's a React app)
[services.frontend]
path = "frontend"
build = "npm install && npm run build"
start = "serve -s build"